version: '3.8'

services:
  # MongoDB service
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: kanwar-sikandar-ali-todo
      MONGO_INITDB_ROOT_PASSWORD: mukarram1361
    ports:
      - "27017:27017"

  # Backend service
  backend-container:
    container_name: backend-container
    image: backend:latest
    restart: always
    environment:
      - MONGODB_URI=mongodb://kanwar-sikandar-ali-todo:mukarram1361@mongo:27017
      - PORT=5000
    ports:
      - "192.168.23.130:5000:5000"
    depends_on:
      - mongo

  # Frontend service
  frontend-container:
    container_name: frontend-container
    image: frontend:latest
    restart: always
    environment:
      - REACT_APP_API_URL=http://192.168.23.130:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend-container
